"""added tag model

Revision ID: 42e9a83e2f2f
Revises: aa3da470f29e
Create Date: 2023-09-08 13:51:54.725751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e9a83e2f2f'
down_revision = 'aa3da470f29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre_tag',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_genre_tag_book_id_books')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_genre_tag_tag_id_tags'))
    )
    op.drop_table('user_books')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('genre')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image')

    op.create_table('user_books',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_user_books_book_id_books'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_books_user_id_users')
    )
    op.drop_table('genre_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
