"""changed genre_tags table to book_tags

Revision ID: d8dad2165e75
Revises: 63dd683495e5
Create Date: 2023-09-25 09:43:23.383623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dad2165e75'
down_revision = '63dd683495e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_tags',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_tags_book_id_books')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_book_tags_tag_id_tags'))
    )
    op.drop_table('bookk_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookk_tags',
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_bookk_tags_book_id_books'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_bookk_tags_tag_id_tags')
    )
    op.drop_table('book_tags')
    # ### end Alembic commands ###
